In [96]:
# step-1  we have to import the dataset to the collab notebook.
import pandas as pd
#pd is nickname of pandas or pd is intance of pandas
df=pd.read_csv('Data.csv')#df(dataframe) is a varaiable ,read_csv is a predefine function from pandas package library and the Data.csv is a dataset which is intance into in the variable df)



In [97]:
type(df)#to identify the varable(df)type

pandas.core.frame.DataFrame

In [98]:
df#it is like print variable to print the data in csv

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [99]:
#step2-grouping the data we have to write 2 varables one for input and another is output
X=df.iloc[:,0:3]
#X is a input variables
#i loc is used for slicing rows and coloums(before comma its rows, after comma coloum sclicing so here we are taking coloums i giving to 0 )

In [100]:
X#input coloums



Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [101]:
Y=df.iloc[:,-1]# Y is a another variable which is for output

In [102]:
Y

0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [103]:
X=X.values#same varable date update and into arrays

In [104]:
X#input into two dimenson array

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [105]:
Y=Y.values#same varables dta update and into arrays

In [106]:
Y# output into two dimensional values

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [107]:
#step-3(handling missing data or values)
#>senario-1:- missing values in numerical columns
#sol:-caluclate mean or Average of the coloum>>we have to write in num.py
#>senario-2:-Missing Values in other than numerical values in column
#sol- fill the with high repeated value.
#>senario-3:-if we have missing values in huge dataset(eg:-20000 records in that 2 rows have empyt values)
#sol:-remove 2those empty values from the dataset.
import numpy as np
from sklearn.impute import SimpleImputer
#sklearn is big library
# simpleimpute(it will use in the fill the blanks in the data) is class  functions which is from sklearn.impute   so we import it
#sklearn is also called as scikit is python libery widely used for machine learning and data moduling
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')#created impute ,ean methods and giving input
imputer.fit(X[:,1:3])#applying prepare for columsby using .fit
X[:,1:3]=imputer.transform(X[:,1:3])#performing actions using transfefuncton replaying insted of nan value to mean value

In [108]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [109]:
#step4:-handling the catagorial data(insted of number there is  text formate is called catagorile data)
#coverting catagorial data to numerical data
from sklearn.preprocessing import OneHotEncoder#it was a librabry in sklearn it is label encoder it is covering text into  numerics
from sklearn.compose import ColumnTransformer# colum transformer is a class imported from sklearn.compose>it is used to apply transeformes or changes to colums
# columTransformer is class which is used to apply the changes of numerical to text
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')#encoder is a method converts text to numerics
X=ct.fit_transform(X)
#OneHotEncoder is only upadte for input columns
#linearencoder is only update for the output colum

In [110]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [111]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
Y=le.fit_transform(Y)

In [112]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [113]:
#step-5:-split the data into training and textin data
from sklearn.model_selection import train_test_split#train_test_split is class which is import from sklearn.model_selection
#which is used to splitting data in testing data and traing data
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)


In [114]:
X_train


array([[0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0]], dtype=object)

In [115]:
X_test

array([[1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0]], dtype=object)

In [116]:
Y_train


array([0, 1, 0, 1, 1, 1, 0, 0])

In [117]:
Y_test


array([1, 0])

In [118]:
#step-6:-features scaling
from sklearn.preprocessing import StandardScaler#
sc=StandardScaler()#sc is a object
X_train[:,3:]=sc.fit_transform(X_train[:,3:])#for scaling
X_test[:,3:]=sc.transform(X_test[:,3:])#for testing

In [119]:
X_train


array([[0.0, 0.0, 1.0, -0.34868047815646297, -0.4133085705197348],
       [1.0, 0.0, 0.0, -0.49723074103968984, 0.11183643672886977],
       [0.0, 1.0, 0.0, 1.4339226764422595, 1.5122231227251486],
       [0.0, 0.0, 1.0, -1.9827333698719587, -1.5511227528917113],
       [1.0, 0.0, 0.0, 1.1368221506758058, 1.162126451226079],
       [0.0, 1.0, 0.0, -0.05157995239000921, -0.17018588197871387],
       [1.0, 0.0, 0.0, 0.5426210991428982, 0.5494572761027069],
       [0.0, 0.0, 1.0, -0.23314138480284194, -1.2010260813926417]],
      dtype=object)

In [120]:
X_test

array([[1.0, 0.0, 0.0, -0.7943312668061436, -0.6758810741440371],
       [0.0, 1.0, 0.0, -1.537082581222278, -1.0259777456431067]],
      dtype=object)

In [121]:
#machine learningtraing the model
# 1. supervisoned Ml>labeled data>classified things(eg:country ,age,salary etcc..)-
#algorithms:-1.linearregulation
#2. logistic regulation
# 2.unsupervisoned ML>unlabeled data>to remember the patterns we can perform prediction
# 3. reinforcement Ml>model will train by using trail and error method (eg:restart throug obstraciles)


In [122]:
#logistic regression algorithm when model perform classification task we have to aplly logistic algorithm(eg:either no or yes)
#linear regression when model perform prediction task we have to apply linear regression algorithm

In [123]:
#step:-7 applying algorithm to the data[traing the model]
from sklearn.linear_model import LogisticRegression
classfier=LogisticRegression()#take object as classfier
classfier.fit(X_train,Y_train)

LogisticRegression()

In [124]:
Y_pred=classfier.predict(X_test)#to text that we use X_testby creating an varible store the obeject in it

In [125]:
Y_pred

array([1, 1])